Update installation-create-node-configuration-files.adoc
[root@rhel79-vm-template-docker ~]# storagegrid node validate
Checking for misnamed node configuration files... PASSED
Checking configuration file /etc/storagegrid/nodes/RHEL-SN2.conf for node RHEL-SN2...
  ERROR:   RHEL-SN2: INTERFACES_TARGET_01 = ens193
           RHEL-SN2: Invalid option: INTERFACES_TARGET_01
Checking for duplication of unique values... PASSED

[Yesterday 4:11 PM] Vyawahare, Ruturaj
    It's INTERFACE_TARGET_01 instead of INTERFACES_TARGET_01. Docs or the product need an update 

I made the change as suggested and now it works.